build:
	go build main.go
run:
	./main start
depends:
	go get "github.com/gorilla/mux"
	go get "github.com/joho/godotenv"
	go get "go.mongodb.org/mongo-driver/bson/primitive"
	go get "go.mongodb.org/mongo-driver/mongo"
	go get "go.mongodb.org/mongo-driver/mongo/options"