name: Deploy dev preview to Heroku (Frontend)

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-dev.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONT_DEV_NAME }}.git
      - name: Deploy frontend dev to Heroku
        run: git push heroku-frontend `git subtree split --prefix frontend main`:refs/heads/main --force
